# Exercise 1

```{r}
for(i in 1:9)
{
    if (i == 9)
    {
        cat("*")
    }

    cat("\n")
}
```

# Exercise 2

```{r}
for(i in 1:10)
{
    cat("*")

    if (i < 10)
    {
        cat("&")
    }
}
```

# Exercise 3

Variable | Start Value | End Value
---- | ---- | ----
dogs | 10 | 15
meatloaf | 0 | -30
bubbles | 12 | -4

\newpage

# Exercise 4

```{r}
years <- c( 2015, 2016, 2018, 2020, 2021)
for(ii in 1:length(years))
{
    if(years[ii] %% 2 == 0)
    {
        cat(years[ii], 'Hooray, congressional elections!', sep = '\t', fill = T)
    }

    if(years[ii] %% 4 == 0)
    {
        cat(years[ii], 'Hooray, presidential elections!', sep = '\t', fill = T)
    }
}
```

# Exercise 5

```{r}
bankAccounts <- c(10, 9.2, 5.6, 3.7, 8.8, 0.5);

interestRate <- 0.0125;
compounded <- rep(0, length(bankAccounts))

for (i in 1:length(bankAccounts))
{
    compounded[i] <- interestRate*bankAccounts[i] + bankAccounts[i]
}

compounded
```

\newpage

# Exercise 6

```{r}
bankAccounts <- c(10, 9.2, 5.6); #define bank accounts here
interestRate <- 0.0525;
house <- c(4.8, 3.8, 5.7); #deduct
food<- c(3.5, 4.3, 5.0);    #deduct
fun <- c(7.8, 2.1, 10.5);  #deduct
#and incomes (through TAships) of 
income <- c(21, 21, 21); #add this

for (j in 1:5)
{
    for (i in 1:length(bankAccounts))
	{
		bankAccounts[i] <- bankAccounts[i] - house[i] - food[i] - fun[i] + income[i]
		bankAccounts[i] <- interestRate*bankAccounts[i] + bankAccounts[i]
    }
}

bankAccounts
```

# Exercise 7

```{r}
bankAccounts <- c(10, 9.2, 5.6); #define bank accounts here
interestRate <- 0.0525;
house <- c(4.8, 3.8, 5.7); #deduct
food<- c(3.5, 4.3, 5.0);    #deduct
fun <- c(7.8, 2.1, 10.5);  #deduct
#and incomes (through TAships) of 
income <- c(21, 21, 21); #add this

for (j in 2015:2020)
{
    for (i in 1:length(bankAccounts))
	{
		bankAccounts[i] <- bankAccounts[i] - house[i] - food[i] - fun[i] + income[i]
		
		if(j%%2 == 1 && i != 2)
		{
			bankAccounts[i] <- bankAccounts[i] + 5
		}
		
		bankAccounts[i] <- interestRate*bankAccounts[i] + bankAccounts[i]
    }
}

bankAccounts
```

\newpage

# Exercise 8

```{r}
i <- 1
sum <- 0

while(i <= 17)
{
	sum <- sum + i
	i <- i + 1
}

sum
```

# Exercise 9

```{r}
Crude_Ruler <- function(num)
{
	if (num < -1)
	{
		cat("small\n")
	}
	else if (num >= -1 && num <= 1)
	{
		cat("medium\n")
	}
	else
	{
		cat("large\n")
	}
}
```
